' Copyright 2026 the contributors of APPXC (github.com/alexander-nbg/appxc)
' SPDX-License-Identifier: 0BSD
@startuml
!include ../../style.puml

|Application|
start
:<b>workflows/test.yml</b>;
|APPXC|
:<b>actions/setup/action.yml</b>(python version)
Plus appxc token as long as not appxc;

|Application|
:<b>actions/setup/action.yml</b>
(optional) for application
specific installations;

|APPXC|
:<b>.github/actions/run-tox</b>
Install, cache venv and run tox.;
|Application|
end
@enduml
