# Copyright 2026 the contributors of APPXC (github.com/alexander-nbg/appxc)
# SPDX-License-Identifier: 0BSD

name: cd

on:
  workflow_dispatch:
  release:
    types:
      - published

# Publish and validate published packages (first testpypi, then pypi).

jobs:
  build:
    uses: ./.github/workflows/reuse-build.yml

  deploy-testpypi:
    needs: build
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-testpypi-${{ github.ref }}
      cancel-in-progress: false
    environment:
      name: testpypi

    steps:
      - name: Download built distributions
        uses: actions/download-artifact@v8
        with:
          name: dist-${{ github.run_id }}
          path: dist/

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/

  validate-testpypi:
    needs: [build, deploy-testpypi]
    uses: ./.github/workflows/validate-deploy.yml
    with:
      target-repository: testpypi
      package-version: ${{ needs.build.outputs['package_version'] }}

  deploy-pypi:
    needs: [build, validate-testpypi]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-pypi-${{ github.ref }}
      cancel-in-progress: false
    environment:
      name: pypi

    steps:
      - name: Download built distributions
        uses: actions/download-artifact@v8
        with:
          name: dist-${{ github.run_id }}
          path: dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

  validate-pypi:
    needs: [build, deploy-pypi]
    uses: ./.github/workflows/validate-deploy.yml
    with:
      target-repository: pypi
      package-version: ${{ needs.build.outputs['package_version'] }}
